# Generated by Django 3.1.5 on 2021-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210623_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='important_detais',
            new_name='important_dates',
        ),
        migrations.AddField(
            model_name='exam',
            name='syllabus',
            field=models.JSONField(null=True),
        ),
    ]
