# Generated by Django 3.1.5 on 2021-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='meta_keywords',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
