# Generated by Django 3.1.5 on 2021-03-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=0),
        ),
    ]
