# Generated by Django 3.1.5 on 2021-03-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_psychometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometry',
            name='academics',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='psychometry',
            name='infrastructure',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='psychometry',
            name='placement',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
