# Generated by Django 3.1.5 on 2021-03-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210318_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=0),
        ),
    ]
