# Generated by Django 3.1.5 on 2021-03-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210323_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometry',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', unique=True),
        ),
    ]
