# Generated by Django 3.1.5 on 2021-03-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210323_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychometry',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
