# Generated by Django 3.1.4 on 2021-05-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210318_2304'),
        ('profiles', '0007_auto_20210323_2330'),
    ]

    operations = [
    ]
