# Generated by Django 3.1.5 on 2021-04-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210323_2330'),
        ('profiles', '0005_auto_20210318_2304'),
    ]

    operations = [
    ]
