# Generated by Django 3.1.5 on 2021-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_merge_20210404_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
