# Generated by Django 3.1.5 on 2021-06-25 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('degree_name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('abbreviated_name', models.CharField(max_length=50, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.JSONField(blank=True, default=[], null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('stream', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('examination_type', models.CharField(max_length=255, null=True)),
                ('avg_course_fees', models.CharField(max_length=255, null=True)),
                ('eligibility', models.TextField(null=True)),
                ('syllabus', models.TextField(null=True)),
                ('career', models.TextField(null=True)),
                ('top_institutes', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_top', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
