# Generated by Django 3.1.5 on 2021-06-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_name',
        ),
    ]
