# Generated by Django 3.1.5 on 2021-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='career',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='top_institutes',
            field=models.JSONField(null=True),
        ),
    ]
