# Generated by Django 3.1.4 on 2020-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='scraping_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
