# Generated by Django 3.1.4 on 2020-12-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college_scraping_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='about',
        ),
        migrations.RemoveField(
            model_name='college',
            name='admission_process',
        ),
        migrations.RemoveField(
            model_name='college',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='college',
            name='degrees',
        ),
        migrations.RemoveField(
            model_name='college',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='college',
            name='placements',
        ),
        migrations.RemoveField(
            model_name='college',
            name='streams',
        ),
    ]
