# Generated by Django 3.1.4 on 2021-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20201227_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='contacts',
        ),
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
