# Generated by Django 3.1.4 on 2021-02-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210202_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='images',
        ),
    ]
