# Generated by Django 3.1.5 on 2021-03-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20210202_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='entrance_exams',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
