# Generated by Django 3.1.4 on 2021-05-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20210504_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='keywords',
        ),
    ]
