# Generated by Django 3.1.4 on 2021-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_college_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='about_us',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
