# Generated by Django 3.1.4 on 2021-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_collegebookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
