# Generated by Django 3.1.5 on 2021-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20210528_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admission_procedure',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='affiliated',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
