# Generated by Django 3.1.5 on 2021-06-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20210609_2119'),
        ('college', '0016_appliedcollege'),
    ]

    operations = [
    ]
