# Generated by Django 3.1.5 on 2021-06-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_merge_20210618_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('created_at',)},
        ),
    ]
