# Generated by Django 3.1.5 on 2021-06-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_auto_20210627_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='meta_keywords',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
