# Generated by Django 3.1.5 on 2021-07-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_auto_20210628_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegenres',
            name='image',
            field=models.ImageField(null=True, upload_to='college_tags/image/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='meta_keywords',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
