# Generated by Django 3.1.5 on 2021-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_auto_20210711_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegenres',
            name='url_tag',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
