# Generated by Django 3.1.5 on 2021-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_auto_20210711_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegenres',
            name='url_tag',
            field=models.CharField(blank=True, default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
