# Generated by Django 3.1.5 on 2021-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0027_auto_20210711_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegenres',
            name='url_tag',
            field=models.CharField(blank=True, default='a', max_length=100),
        ),
    ]
