# Generated by Django 3.1.5 on 2021-07-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0028_collegegenres_url_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegegenres',
            name='url_tag',
        ),
    ]
