# Generated by Django 3.1.4 on 2021-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_remove_collegegenres_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
