# Generated by Django 3.1.5 on 2021-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_remove_collegegenres_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegenres',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_tags/image/'),
        ),
        migrations.AddField(
            model_name='collegegenres',
            name='url_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
