# Generated by Django 3.1.4 on 2021-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_collegegenres_popular_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='detailed_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
