# Generated by Django 3.1.4 on 2020-12-21 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('comment', models.TextField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.IntegerField(choices=[(1, 'Google'), (2, 'Shiksha'), (3, 'College Dunia'), (4, 'College Search'), (5, 'Get My Uni'), (6, 'Self'), (0, 'Other')])),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('overall', models.FloatField(blank=True, null=True)),
                ('infrastructure', models.FloatField(blank=True, null=True)),
                ('placement', models.FloatField(blank=True, null=True)),
                ('academics', models.FloatField(blank=True, null=True)),
                ('value_for_money', models.FloatField(blank=True, null=True)),
                ('campus_life', models.FloatField(blank=True, null=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
