# Generated by Django 3.1.4 on 2021-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='source',
            field=models.IntegerField(choices=[(1, 'Google'), (2, 'Shiksha'), (3, 'College Dunia'), (4, 'College Search'), (5, 'Get My Uni'), (6, 'Self'), (7, 'Career360'), (0, 'Other')]),
        ),
    ]
