# Generated by Django 3.1.5 on 2021-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
