# Generated by Django 3.1.4 on 2021-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210528_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='quadrants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
