# Generated by Django 3.1.4 on 2021-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_quadrants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='quadrants',
            new_name='detailed_quadrants',
        ),
        migrations.AddField(
            model_name='review',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
