# Generated by Django 3.1.4 on 2021-07-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210718_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='detailed_quadrants',
            new_name='quadrants',
        ),
        migrations.RemoveField(
            model_name='review',
            name='metrics',
        ),
    ]
