# Generated by Django 3.1.4 on 2021-07-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0032_college_detailed_metrics'),
        ('reviews', '0005_auto_20210718_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('college', 'comment', 'source')},
        ),
    ]
